name = "ningyi-tech-website"
type = "javascript"
compatibility_date = "2026-05-21"

[build]
command = "pnpm build"
cwd = "./"

[env.production]
name = "ningyi-tech-website-prod"

[[build.upload]]
format = "service-worker"

[build.upload.rules]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true
